env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "dist"
rules:
  # Just don't like these rules
  "import/prefer-default-export": 0
  "no-plusplus": 0
  "no-underscore-dangle": 0

  # TODO: remove this rule override
  "no-console": 0
